In [1]:
!git clone https://github.com/aycakrk/DI725_Ayca.git

Cloning into 'DI725_Ayca'...
remote: Enumerating objects: 183, done.
remote: Counting objects: 100% (183/183), done.
remote: Compressing objects: 100% (129/129), done.
remote: Total 183 (delta 60), reused 167 (delta 47), pack-reused 0 (from 0)
Receiving objects: 100% (183/183), 2.21 MiB | 18.70 MiB/s, done.
Resolving deltas: 100% (60/60), done.


In [2]:
!python /content/DI725_Ayca/assignment_1/data/customer_service/prepare.py


Original: Test encoding and decoding!
Encoded: [53, 70, 84, 85, 1, 70, 79, 68, 80, 69, 74, 79, 72, 1, 66, 79, 69, 1, 69, 70, 68, 80, 69, 74, 79, 72, 2]
Decoded: Test encoding and decoding!


In [3]:
import numpy as np

train_data = np.load('/content/DI725_Ayca/assignment_1/data/customer_service/train_data.npy', allow_pickle=True)
train_labels = np.load('/content/DI725_Ayca/assignment_1/data/customer_service/train_labels.npy', allow_pickle=True)
val_data = np.load('/content/DI725_Ayca/assignment_1/data/customer_service/val_data.npy', allow_pickle=True)
val_labels = np.load('/content/DI725_Ayca/assignment_1/data/customer_service/val_labels.npy', allow_pickle=True)

print(len(train_data), len(train_labels))   # Aynı sayıda olmalı
print(train_data[3])     # 0. konuşmanın tokenları
print(train_labels[3])   # 0. konuşmanın etiketi



873 873
[73, 70, 77, 77, 80, 1, 74, 1, 88, 66, 79, 85, 1, 85, 80, 1, 83, 70, 85, 86, 83, 79, 1, 66, 1, 88, 66, 84, 73, 74, 79, 72, 1, 78, 66, 68, 73, 74, 79, 70, 1, 85, 73, 66, 85, 1, 74, 1, 83, 70, 68, 70, 74, 87, 70, 69, 1, 67, 86, 85, 1, 74, 85, 1, 74, 84, 1, 79, 80, 85, 1, 85, 73, 70, 1, 80, 79, 70, 1, 74, 1, 80, 83, 69, 70, 83, 70, 69, 15, 1, 90, 70, 84, 1, 78, 90, 1, 80, 83, 69, 70, 83, 1, 79, 86, 78, 67, 70, 83, 1, 74, 84, 1, 67, 67, 15, 1, 74, 1, 80, 83, 69, 70, 83, 70, 69, 1, 66, 1, 71, 83, 80, 79, 85, 77, 80, 66, 69, 74, 79, 72, 1, 88, 66, 84, 73, 74, 79, 72, 1, 78, 66, 68, 73, 74, 79, 70, 1, 67, 86, 85, 1, 74, 1, 83, 70, 68, 70, 74, 87, 70, 69, 1, 66, 1, 85, 80, 81, 77, 80, 66, 69, 74, 79, 72, 1, 80, 79, 70, 1, 74, 79, 84, 85, 70, 66, 69, 15, 1, 79, 80, 1, 85, 73, 70, 1, 80, 86, 85, 70, 83, 1, 67, 80, 89, 1, 88, 66, 84, 1, 74, 79, 85, 66, 68, 85, 1, 66, 79, 69, 1, 85, 73, 70, 83, 70, 1, 88, 66, 84, 1, 79, 80, 1, 69, 66, 78, 66, 72, 70, 1, 85, 80, 1, 74, 85, 15, 1, 84, 86, 83

In [13]:
!python /content/DI725_Ayca/assignment_1/train.py /content/DI725_Ayca/assignment_1/config/train_customer.py --compile=False --save_path=checkpoint.pt


Using device = cuda
Loaded vocab_size = 96
iter 0: loss 5.7056
/content/DI725_Ayca/assignment_1/train.py:46: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:254.)
  X_torch = torch.tensor(X_list, dtype=torch.long, device=device)
iter 50: loss 3.4435
iter 100: loss 3.2943
iter 150: loss 3.2545
iter 200: loss 3.1022
Step 200: val_loss = 3.1019
iter 250: loss 3.0164
iter 300: loss 2.6995
iter 350: loss 3.0490
iter 400: loss 2.5322
Step 400: val_loss = 2.9477
iter 450: loss 2.6994
iter 500: loss 2.8688
iter 550: loss 2.6840
iter 600: loss 2.6021
Step 600: val_loss = 3.1924
iter 650: loss 2.3061
iter 700: loss 2.3368
iter 750: loss 2.9863
iter 800: loss 2.3428
Step 800: val_loss = 3.0709
iter 850: loss 2.4221
iter 900: loss 2.2082
iter 950: loss 2.5381
iter 1000: loss 2.2601
Step 1000

In [17]:
!python /content/DI725_Ayca/assignment_1/test.py /content/DI725_Ayca/assignment_1/config/train_customer.py --checkpoint=checkpoint.pt


Using device = cuda
Loaded vocab_size = 96
Checkpoint yüklendi: checkpoint.pt
Confusion Matrix (rows=TRUE, cols=PRED) [neg, neu, pos]:
[[8 2 0]
 [2 8 0]
 [2 8 0]]

Classification Report:
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted 

added more weight to positive labels

In [31]:
!python /content/DI725_Ayca/assignment_1/train.py /content/DI725_Ayca/assignment_1/config/train_customer.py --compile=False --save_path=checkpoint2.pt


Using device = cuda
Loaded vocab_size = 96
iter 0: loss 5.7528
iter 50: loss 3.4821
/content/DI725_Ayca/assignment_1/train.py:46: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:254.)
  X_torch = torch.tensor(X_list, dtype=torch.long, device=device)
iter 100: loss 3.3737
iter 150: loss 3.2090
iter 200: loss 3.1686
Step 200: val_loss = 3.3452
iter 250: loss 2.9768
iter 300: loss 4.1611
iter 350: loss 2.7131
iter 400: loss 2.8425
Step 400: val_loss = 3.1809
iter 450: loss 2.7831
iter 500: loss 2.7528
iter 550: loss 3.3954
iter 600: loss 2.8031
Step 600: val_loss = 3.0904
iter 650: loss 2.6730
iter 700: loss 3.7660
iter 750: loss 3.6417
iter 800: loss 2.8734
Step 800: val_loss = 3.5355
iter 850: loss 2.8035
iter 900: loss 2.5300
iter 950: loss 2.4000
iter 1000: loss 2.3253
Step 1000

In [32]:
!python /content/DI725_Ayca/assignment_1/test.py /content/DI725_Ayca/assignment_1/config/train_customer.py --checkpoint=checkpoint2.pt


Using device = cuda
Loaded vocab_size = 96
Checkpoint yüklendi: checkpoint2.pt
Confusion Matrix (rows=TRUE, cols=PRED) [neg, neu, pos]:
[[10  0  0]
 [ 4  6  0]
 [ 6  3  1]]

Classification Report:
              precision    recall  f1-score   support

    Negative     0.5000    1.0000    0.6667        10
     Neutral     0.6667    0.6000    0.6316        10
    Positive     1.0000    0.1000    0.1818        10

    accuracy                         0.5667        30
   macro avg     0.7222    0.5667    0.4934        30
weighted avg     0.7222    0.5667    0.4934        30



In [33]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!cp /content/drive/MyDrive/ColabNotebooks/DataExploration_PreProcessing.ipynb /content/DI725_Ayca/assignment_1